version: '3'

services:
  #Database
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_USERNAME: kiki
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql
    networks:
      - vendorSite
  #phpmyadmin
  apache:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - vendorSite
  #api
  api:
    image: andrewokiki/api:v1.0
    restart: always
    ports:
      - 3000:3000
    networks:
      - vendorSite
    depends_on:
      - db
      - apache
networks:
  vendorSite:
    driver: bridge

